:concurrency: 3
:timeout: 60
:verbose: true
:queues:  # Queue priority: https://github.com/mperham/sidekiq/wiki/Advanced-Options
  - default
  - mailers
  - webhook
:schedule:
  notifications:
    cron: '05 11 * * 3'   # 0 0 12 ? * THU *      for every friday at 12 pm   5 12 * * 5
    class: NotificationsSchedulerJob
